// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForWebDevelopmentTesting123456789',
    appId: '1:123456789:web:abcdef123456789abcdef1',
    messagingSenderId: '123456789',
    projectId: 'kobe-scan-demo',
    authDomain: 'kobe-scan-demo.firebaseapp.com',
    storageBucket: 'kobe-scan-demo.appspot.com',
    measurementId: 'G-MEASUREMENT123',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForAndroidDevelopmentTesting123456',
    appId: '1:123456789:android:abcdef123456789abcdef1',
    messagingSenderId: '123456789',
    projectId: 'kobe-scan-demo',
    storageBucket: 'kobe-scan-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForIosDevelopmentTesting123456789',
    appId: '1:123456789:ios:abcdef123456789abcdef1',
    messagingSenderId: '123456789',
    projectId: 'kobe-scan-demo',
    storageBucket: 'kobe-scan-demo.appspot.com',
    iosBundleId: 'com.example.kobeScanApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForMacosDevelopmentTesting123456',
    appId: '1:123456789:ios:abcdef123456789abcdef2',
    messagingSenderId: '123456789',
    projectId: 'kobe-scan-demo',
    storageBucket: 'kobe-scan-demo.appspot.com',
    iosBundleId: 'com.example.kobeScanApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'your-windows-api-key',
    appId: 'your-windows-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'kobescanapp',
    authDomain: 'kobescanapp.firebaseapp.com',
    storageBucket: 'kobescanapp.appspot.com',
    measurementId: 'your-measurement-id',
  );
}
